### ISSUE TITLE
Deprecation in action

### ISSUE THREAD

**Issue by Czaki** [chanzuckerberg/napari-hub-preview-action#6]
in logs of action there are information about two deprections:

1)
>  Preview Page Deploy
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout@v2, actions/setup-python@v2, actions/setup-node@v2, actions/cache@v2, actions/upload-artifact@v2

2)
> Preview Page Deploy
The `save-state` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

here example run: https://github.com/4DNucleome/PartSeg/actions/runs/3796073246

**Comment by Czaki** [comment]
Any update? @neuromusic?

**Comment by richaagarwal** [comment]
Closing this due to a planned upcoming deprecation (see https://github.com/chanzuckerberg/napari-hub/discussions/1216)
